language: python
sudo: false
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
    os: linux
  - python: 3.5
    env: TOXENV=py35
    os: linux
  - python: 3.6
    env: TOXENV=py36
    os: linux
    after_success:
    - pwd
    - coveralls --data_file rstoolbox/tests/.coverage
    - python-codacy-coverage -r /tmp/cov-single.xml
    - bash <(curl -s https://codecov.io/bash) -Z -c -f /tmp/cov-single.xml
  - python: 3.7-dev
    env: TOXENV=py37
    os: linux
  - language: generic
    env: TOXENV=py27
    os: osx
  - language: generic
    env: TOXENV=py36
    os: osx
before_install:
- bash ./ci/travis_before_install.sh
install:
- bash ./ci/travis_install.sh
script:
- tox
deploy:
  provider: pypi
  user: jaume.bonet
  password:
    secure: Mc0ZDv9HKLAqFneaDU6xknIXnXY+aojY8VOyEEPu93fHABSxjvlkgcoggJHL8y5bag34caWoIGixFI4/slfuf+PUJNLIgm6AqgXpxKsU+gtXwQnEFwKLw65fLz0bCP5GPfPPeH811ZknD5AAw/e8tBYTI81EGh5TM/Y8OBtma4VgU8OrWbNX5gqxxHik/BAZZZh2bDRWq7syMBt5uUvw7rvx7ArDANWjXYcPwPoqVf5D+LY9P6lUBXDPes2lA7D2mk0ids2KojZLT4hI6U2+FwykRbdO7cMxrMYgVgs/oqpsr7tYkZeY16+56mJbt41V7/ofUNndJuaTPcjgLoaN2Ffi4DN7OvMC/CIOR2zyM/fU6SRBaHkT4KQuTMwUq2sw2BTUDMXSsYbn+fh8gc7Pq0EZ1OfDr8fdJRZL6LuwChjrinIh9gjSrZI21Wf1hSx/qwopG8WIl/CP8DXPzC/L2UKKlSBW5Squ5eHOzYRlWedeBxoky9nNCw8ryvzMiWGh36ZgCWT4QK0jWsYI28FIBf2sTyYqqTVimvpWwSVapgO2ZgKaH+tcn+ru2RKARHJBm1W7QVsOIsLop9GRsYwx7o1DsiLFM30r7AzbHpFWcTBzqQ33mdBi/7/bvhz/ExTOqbdEo7FFp1jzFW02DltHy8zBZp6s57bryDETTJT20bc=
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION == '3.6' && $TRAVIS_OS_NAME == "linux"
